// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/durian-dashboard/Accessibility.tsx": () => import("../components/mockups/durian-dashboard/Accessibility.tsx"),
  "./components/mockups/durian-dashboard/Hierarchy.tsx": () => import("../components/mockups/durian-dashboard/Hierarchy.tsx"),
  "./components/mockups/durian-dashboard/Interaction.tsx": () => import("../components/mockups/durian-dashboard/Interaction.tsx")
};
